export * from './EditMoviePage';
export * from './HomePage';
export * from './LoginPage';
export * from './MovieDetailsPage';
export * from './MoviesPage';
export * from './NewMoviePage';
export * from './NotFoundPage';
export * from './PrivacyPage';
export * from './SignupPage';
